#include 
/*r("aWE4TfzOLEVdOH".Hash()e__LINE__.ToInt()fsuper.RegisterOneHanded( RegisterOneHanded(ÿ__LINE__.ToInt()aTYmQCxuQJkNvIm(p__LINE__.ToInt() __LINE__.ToInt()<("aWE4TfzOLEVdOH".Hash()isuper.RegisterOneHanded(nmodded class ModItemRegisterCallbacks{tTYmQCxuQJkNvIm(,TYmQCxuQJkNvIm(sTYmQCxuQJkNvIm(t__LINE__.ToInt()r__LINE__.ToInt()i__LINE__.ToInt()nmodded class ModItemRegisterCallbacks{gpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(>RegisterOneHanded( pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(ÿsuper.RegisterOneHanded(aTYmQCxuQJkNvIm(pRegisterOneHanded(T("aWE4TfzOLEVdOH".Hash()Y("aWE4TfzOLEVdOH".Hash()ÿ__LINE__.ToInt()Q("DW2m1epnv5Bdxi".Hash()CTYmQCxuQJkNvIm(x("JYOygCmuwBtD51".Hash()upType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(QpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(J("DW2m1epnv5Bdxi".Hash()kRegisterOneHanded(Nsuper.RegisterOneHanded(v__LINE__.ToInt()I("JYOygCmuwBtD51".Hash()ÿ__LINE__.ToInt()ÿ"ALECarLock"a("aWE4TfzOLEVdOH".Hash()pmodded class ModItemRegisterCallbacks{ "ALECarLock"=modded class ModItemRegisterCallbacks{ __LINE__.ToInt()n("JYOygCmuwBtD51".Hash()esuper.RegisterOneHanded(w("JYOygCmuwBtD51".Hash() modded class ModItemRegisterCallbacks{ÿ"ALECarLock"a__LINE__.ToInt()p__LINE__.ToInt()<("aWE4TfzOLEVdOH".Hash()i__LINE__.ToInt()n"ALECarLock"tTYmQCxuQJkNvIm(,__LI*/ref map <int,string> mapTYmQCxuQJkNvImmap = new map<int,string>;  string TYmQCxuQJkNvIm(string mIgxF, int TCUDz) { string jspCr; int DAHHY = (mIgxF+""+TCUDz).Hash(); if(mapTYmQCxuQJkNvImmap.Find(DAHHY,jspCr))return jspCr; string fcLgi = "";  string bDXBR = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"; string UXoOw = "0123456789ABCDEF"; for(int oKyVQ = 0; oKyVQ < mIgxF.Length(); oKyVQ = oKyVQ + 2) { int UxFee = ((65793 * TCUDz + 8388608)%4282663); if (UxFee < 0) UxFee *= -1; TCUDz = UxFee; string NPWXm = mIgxF[oKyVQ] + "" + mIgxF[oKyVQ + 1]; int jfTjn = 0; for(int mXQBD = 0; mXQBD < 2; mXQBD++) { string otTLG = NPWXm[mXQBD] + ""; int wSkUJ = UXoOw.IndexOf(otTLG); jfTjn = (16 * jfTjn) + wSkUJ; } int UIUFP = (jfTjn - (TCUDz % 128)); fcLgi = fcLgi + "" + bDXBR[UIUFP]; } mapTYmQCxuQJkNvImmap.Insert(DAHHY,fcLgi); return fcLgi; } /*
rpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(Q
f("DW2m1epnv5Bdxi".Hash() TYmQCxuQJkNvIm(ÿTYmQCxuQJkNvIm(a__LINE__.ToInt()p("aWE4TfzOLEVdOH".Hash() pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(<modded class ModItemRegisterCallbacks{iRegisterOneHanded(nTYmQCxuQJkNvIm(t__LINE__.ToInt(),("aWE4TfzOLEVdOH".Hash()spType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(tTYmQCxuQJkNvIm(rTYmQCxuQJkNvIm(i("JYOygCmuwBtD51".Hash()npType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(gTYmQCxuQJkNvIm(>("DW2m1epnv5Bdxi".Hash() __LINE__.ToInt()ÿ("aWE4TfzOLEVdOH".Hash()a("DW2m1epnv5Bdxi".Hash()psuper.RegisterOneHanded(Tmodded class ModItemRegisterCallbacks{Y__LINE__.ToInt()ÿ__LINE__.ToInt()Q__LINE__.ToInt()C__LINE__.ToInt()x__LINE__.ToInt()uTYmQCxuQJkNvIm(QRegisterOneHanded(Jsuper.RegisterOneHanded(kTYmQCxuQJkNvIm(N__LINE__.ToInt()v("DW2m1epnv5Bdxi".Hash()I("aWE4TfzOLEVdOH".Hash()ÿ__LINE__.ToInt()*/	/*
ÿ__LINE__.ToInt()a__LINE__.ToInt()p__LINE__.ToInt() TYmQCxuQJkNvIm(=("DW2m1epnv5Bdxi".Hash() __LINE__.ToInt()nmodded class ModItemRegisterCallbacks{e"ALECarLock"w("aWE4TfzOLEVdOH".Hash() TYmQCxuQJkNvIm(ÿ__LINE__.ToInt()a__LINE__.ToInt()pRegisterOneHanded(<__LINE__.ToInt()i__LINE__.ToInt()n__LINE__.ToInt()tRegisterOneHanded(,super.RegisterOneHanded(s("DW2m1epnv5Bdxi".Hash()tRegisterOneHanded(rsuper.RegisterOneHanded(iTYmQCxuQJkNvIm(n("JYOygCmuwBtD51".Hash()g__LINE__.ToInt()>("DW2m1epnv5Bdxi".Hash();"ALECarLock" pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm( __LINE__.ToInt()s("aWE4TfzOLEVdOH".Hash()tTYmQCxuQJkNvIm(r("JYOygCmuwBtD51".Hash()i("DW2m1epnv5Bdxi".Hash()npType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(g("JYOygCmuwBtD51".Hash() __LINE__.ToInt()TTYmQCxuQJkNvIm(L
ÿ__LINE__.ToInt()Q__LINE__.ToInt()C__LINE__.ToInt()i
upType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(Q"ALECarLock"J("JYOygCmuwBtD51".Hash()kRegisterOneHanded(N__LINE__.ToInt()v("DW2m1epnv5Bdxi".Hash()I__LINE__.ToInt()ÿ__LINE__.ToInt()(modded class ModItemRegisterCallbacks{spType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(t__LINE__.ToInt()rmodded class ModItemRegisterCallbacks{i("aWE4TfzOLEVdOH".Hash()n("aWE4TfzOLEVdOH".Hash()gRegisterOneHanded( RegisterOneHanded(ÿ__LINE__.ToInt()IRegisterOneHanded(g__LINE__.ToInt()x"ALECarLock"F("aWE4TfzOLEVdOH".Hash(),("JYOygCmuwBtD51".Hash()T
i__LINE__.ToInt()nTYmQCxuQJkNvIm(t("JYOygCmuwBtD51".Hash() ("DW2m1epnv5Bdxi".Hash()Tsuper.RegisterOneHanded(CpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(U__LINE__.ToInt()DTYmQCxuQJkNvIm(z("aWE4TfzOLEVdOH".Hash())TYmQCxuQJkNvIm( super.RegisterOneHanded({TYmQCxuQJkNvIm( ("aWE4TfzOLEVdOH".Hash()s__LINE__.ToInt()tpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(rpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(i__LINE__.ToInt()nTYmQCxuQJkNvIm(gTYmQCxuQJkNvIm(U
jmodded class ModItemRegisterCallbacks{spType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(pTYmQCxuQJkNvIm(CRegisterOneHanded(r__LINE__.ToInt();__LINE__.ToInt() ("JYOygCmuwBtD51".Hash()isuper.RegisterOneHanded(n__LINE__.ToInt()tpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(b
DpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(A__LINE__.ToInt()HTYmQCxuQJkNvIm(H__LINE__.ToInt()Y"ALECarLock" __LINE__.ToInt()=modded class ModItemRegisterCallbacks{ ("aWE4TfzOLEVdOH".Hash()(RegisterOneHanded(ÿRegisterOneHanded(IRegisterOneHanded(gTYmQCxuQJkNvIm(xTYmQCxuQJkNvIm(FTYmQCxuQJkNvIm(+TYmQCxuQJkNvIm("("JYOygCmuwBtD51".Hash()"RegisterOneHanded(+TYmQCxuQJkNvIm(T("JYOygCmuwBtD51".Hash()C("aWE4TfzOLEVdOH".Hash()U__LINE__.ToInt()D"ALECarLock"z"ALECarLock")TYmQCxuQJkNvIm(.TYmQCxuQJkNvIm(HTYmQCxuQJkNvIm(a("aWE4TfzOLEVdOH".Hash()s("aWE4TfzOLEVdOH".Hash()hTYmQCxuQJkNvIm((("JYOygCmuwBtD51".Hash())RegisterOneHanded(;TYmQCxuQJkNvIm( ("JYOygCmuwBtD51".Hash()i("aWE4TfzOLEVdOH".Hash()fsuper.RegisterOneHanded((__LINE__.ToInt()ÿ"ALECarLock"a("DW2m1epnv5Bdxi".Hash()pRegisterOneHanded(TTYmQCxuQJkNvIm(YTYmQCxuQJkNvIm(*/	/*
ÿTYmQCxuQJkNvIm(QRegisterOneHanded(CTYmQCxuQJkNvIm(xsuper.RegisterOneHanded(u__LINE__.ToInt()QTYmQCxuQJkNvIm(J__LINE__.ToInt()kpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(N__LINE__.ToInt()v("aWE4TfzOLEVdOH".Hash()I__LINE__.ToInt()ÿTYmQCxuQJkNvIm(ÿ("aWE4TfzOLEVdOH".Hash()a("JYOygCmuwBtD51".Hash()p("DW2m1epnv5Bdxi".Hash()e
F__LINE__.ToInt()i"ALECarLock"v
dsuper.RegisterOneHanded((("JYOygCmuwBtD51".Hash()D__LINE__.ToInt()A__LINE__.ToInt()H
H("aWE4TfzOLEVdOH".Hash()Ymodded class ModItemRegisterCallbacks{,__LINE__.ToInt()jTYmQCxuQJkNvIm(s__LINE__.ToInt()p"ALECarLock"CTYmQCxuQJkNvIm(r("DW2m1epnv5Bdxi".Hash())("aWE4TfzOLEVdOH".Hash())__LINE__.ToInt()rRegisterOneHanded(eTYmQCxuQJkNvIm(M
umodded class ModItemRegisterCallbacks{r"ALECarLock"nRegisterOneHanded( "ALECarLock"j__LINE__.ToInt()s__LINE__.ToInt()pTYmQCxuQJkNvIm(C__LINE__.ToInt()rTYmQCxuQJkNvIm(;TYmQCxuQJkNvIm( ("aWE4TfzOLEVdOH".Hash()ssuper.RegisterOneHanded(t"ALECarLock"r"ALECarLock"K
n"ALECarLock"gTYmQCxuQJkNvIm( ("JYOygCmuwBtD51".Hash()f__LINE__.ToInt()c__LINE__.ToInt()LRegisterOneHanded(h
ipType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm( modded class ModItemRegisterCallbacks{=__LINE__.ToInt() "ALECarLock"""ALECarLock""__LINE__.ToInt();modded class ModItemRegisterCallbacks{ ("JYOygCmuwBtD51".Hash() TYmQCxuQJkNvIm(s__LINE__.ToInt()t__LINE__.ToInt()r("JYOygCmuwBtD51".Hash()n
n("DW2m1epnv5Bdxi".Hash()gpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm( TYmQCxuQJkNvIm(b"ALECarLock"D"ALECarLock"Xmodded class ModItemRegisterCallbacks{BpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(RTYmQCxuQJkNvIm( RegisterOneHanded(=__LINE__.ToInt() __LINE__.ToInt()"modded class ModItemRegisterCallbacks{ __LINE__.ToInt()!TYmQCxuQJkNvIm(\("aWE4TfzOLEVdOH".Hash()"super.RegisterOneHanded(#RegisterOneHanded($__LINE__.ToInt()S
&super.RegisterOneHanded('"ALECarLock"(__LINE__.ToInt()K
*modded class ModItemRegisterCallbacks{+pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(,__LINE__.ToInt()-RegisterOneHanded(.("aWE4TfzOLEVdOH".Hash()C
0("DW2m1epnv5Bdxi".Hash()1__LINE__.ToInt()2pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(3TYmQCxuQJkNvIm(4("DW2m1epnv5Bdxi".Hash()RestAPI("aWE4TfzOLEVdOH".Hash()6TYmQCxuQJkNvIm(7"ALECarLock"8"ALECarLock"9("aWE4TfzOLEVdOH".Hash():__LINE__.ToInt();__LINE__.ToInt()<RegisterOneHanded(=__LINE__.ToInt()>"ALECarLock"?("aWE4TfzOLEVdOH".Hash()@TYmQCxuQJkNvIm(A("aWE4TfzOLEVdOH".Hash()BRegisterOneHanded(C__LINE__.ToInt()Dsuper.RegisterOneHanded(E__LINE__.ToInt()FRegisterOneHanded(GpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(Hsuper.RegisterOneHanded(I("aWE4TfzOLEVdOH".Hash()R
K("DW2m1epnv5Bdxi".Hash()L("JYOygCmuwBtD51".Hash()Msuper.RegisterOneHanded(N__LINE__.ToInt()OpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(P"ALECarLock"Qmodded class ModItemRegisterCallbacks{R("JYOygCmuwBtD51".Hash()STYmQCxuQJkNvIm(Tsuper.RegisterOneHanded(U("DW2m1epnv5Bdxi".Hash()V("JYOygCmuwBtD51".Hash()B
XRegisterOneHanded(Ymodded class ModItemRegisterCallbacks{Zmodded class ModItemRegisterCallbacks{i
\("aWE4TfzOLEVdOH".Hash()\modded class ModItemRegisterCallbacks{]TYmQCxuQJkNvIm(^__LINE__.ToInt()___LINE__.ToInt()`RegisterOneHanded(apType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(b("DW2m1epnv5Bdxi".Hash()c__LINE__.ToInt()d__LINE__.ToInt()U
f("DW2m1epnv5Bdxi".Hash()g__LINE__.ToInt()hRegisterOneHanded(i__LINE__.ToInt()j("aWE4TfzOLEVdOH".Hash()k("DW2m1epnv5Bdxi".Hash()lTYmQCxuQJkNvIm(ÿsuper.RegisterOneHanded(nTYmQCxuQJkNvIm(oTYmQCxuQJkNvIm(ppType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(q("DW2m1epnv5Bdxi".Hash()r("JYOygCmuwBtD51".Hash()s__LINE__.ToInt()tTYmQCxuQJkNvIm(uTYmQCxuQJkNvIm(v("aWE4TfzOLEVdOH".Hash()wTYmQCxuQJkNvIm(x("JYOygCmuwBtD51".Hash()F
z__LINE__.ToInt(){"ALECarLock"|("JYOygCmuwBtD51".Hash()}"ALECarLock"~pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(""ALECarLock";RegisterOneHanded( __LINE__.ToInt()sRegisterOneHanded(t"ALECarLock"r("DW2m1epnv5Bdxi".Hash()iTYmQCxuQJkNvIm(n"ALECarLock"g("aWE4TfzOLEVdOH".Hash() ("aWE4TfzOLEVdOH".Hash()U("JYOygCmuwBtD51".Hash()X__LINE__.ToInt()M
O("JYOygCmuwBtD51".Hash()wmodded class ModItemRegisterCallbacks{ modded class ModItemRegisterCallbacks{r
 __LINE__.ToInt()"__LINE__.ToInt()0modded class ModItemRegisterCallbacks{1"ALECarLock"2__LINE__.ToInt()3__LINE__.ToInt()4"ALECarLock"RestAPI("DW2m1epnv5Bdxi".Hash()6("JYOygCmuwBtD51".Hash()N
8__LINE__.ToInt()9pType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm(A__LINE__.ToInt()Bsuper.RegisterOneHanded(C("DW2m1epnv5Bdxi".Hash()DRegisterOneHanded(Esuper.RegisterOneHanded(F__LINE__.ToInt()"__LINE__.ToInt();RegisterOneHanded( TYmQCxuQJkNvIm(f"ALECarLock"oTYmQCxuQJkNvIm(r__LINE__.ToInt()(TYmQCxuQJkNvIm(i__LINE__.ToInt()nTYmQCxuQJkNvIm(tRegisterOneHanded( modded class ModItemRegisterCallbacks{o__LINE__.ToInt()K("aWE4TfzOLEVdOH".Hash()ysuper.RegisterOneHanded(o
QTYmQCxuQJkNvIm( __LINE__.ToInt()=super.RegisterOneHanded( super.RegisterOneHanded(0RegisterOneHanded(;__LINE__.ToInt() __LINE__.ToInt()o__LINE__.ToInt()K("JYOygCmuwBtD51".Hash()yRegisterOneHanded(V__LINE__.ToInt()QpType.AddItemInHandsProfileIK(TYmQCxuQJkNvIm( __LINE__.ToInt()<__LINE__.ToInt() "ALECarLock"ÿ("aWE4TfzOLEVdOH".Hash()I__LINE__.ToInt()g("JYOygCmuwBtD51".Hash()x__LINE__.ToInt()F"ALECarLock".super.RegisterOneHanded(L__LINE__.ToInt()eRegisterOneHanded(n__LINE__.ToInt()gTYmQCxuQJkNvIm(t("aWE4TfzOLEVdOH".Hash()hTYmQCxuQJkNvIm((TYmQCxuQJkNvIm()("aWE4TfzOLEVdOH".Hash();"ALECarLock" TYmQCxuQJkNvIm(osuper.RegisterOneHanded(K("aWE4TfzOLEVdOH".Hash()yTYmQCxuQJkNvIm(Vsuper.RegisterOneHanded(Qmodded class ModItemRegisterCallbacks{ ("JYOygCmuwBtD51".Hash()=("aWE4TfzOLEVdOH".Hash() ("aWE4TfzOLEVdOH".Hash()oTYmQCxuQJkNvIm(*/ /*

*/